services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      PYTHONUNBUFFERED: "1"
      CORS_ORIGINS: "http://localhost:8080,http://127.0.0.1:8080"

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    depends_on:
      - backend
